/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VocabularioRouteImport } from './routes/vocabulario'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as LiveRouteImport } from './routes/live'
import { Route as FlashcardsRouteImport } from './routes/flashcards'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CuriosidadesRouteImport } from './routes/curiosidades'
import { Route as ConversaRouteImport } from './routes/conversa'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiVocabRouteImport } from './routes/api/vocab'
import { Route as ApiTtsRouteImport } from './routes/api/tts'
import { Route as ApiCuriosidadeRouteImport } from './routes/api/curiosidade'
import { Route as ApiCheckRouteImport } from './routes/api/check'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const VocabularioRoute = VocabularioRouteImport.update({
  id: '/vocabulario',
  path: '/vocabulario',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const FlashcardsRoute = FlashcardsRouteImport.update({
  id: '/flashcards',
  path: '/flashcards',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CuriosidadesRoute = CuriosidadesRouteImport.update({
  id: '/curiosidades',
  path: '/curiosidades',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversaRoute = ConversaRouteImport.update({
  id: '/conversa',
  path: '/conversa',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVocabRoute = ApiVocabRouteImport.update({
  id: '/api/vocab',
  path: '/api/vocab',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTtsRoute = ApiTtsRouteImport.update({
  id: '/api/tts',
  path: '/api/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCuriosidadeRoute = ApiCuriosidadeRouteImport.update({
  id: '/api/curiosidade',
  path: '/api/curiosidade',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCheckRoute = ApiCheckRouteImport.update({
  id: '/api/check',
  path: '/api/check',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/conversa': typeof ConversaRoute
  '/curiosidades': typeof CuriosidadesRoute
  '/dashboard': typeof DashboardRoute
  '/flashcards': typeof FlashcardsRoute
  '/live': typeof LiveRoute
  '/quiz': typeof QuizRoute
  '/vocabulario': typeof VocabularioRoute
  '/api/chat': typeof ApiChatRoute
  '/api/check': typeof ApiCheckRoute
  '/api/curiosidade': typeof ApiCuriosidadeRoute
  '/api/tts': typeof ApiTtsRoute
  '/api/vocab': typeof ApiVocabRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/conversa': typeof ConversaRoute
  '/curiosidades': typeof CuriosidadesRoute
  '/dashboard': typeof DashboardRoute
  '/flashcards': typeof FlashcardsRoute
  '/live': typeof LiveRoute
  '/quiz': typeof QuizRoute
  '/vocabulario': typeof VocabularioRoute
  '/api/chat': typeof ApiChatRoute
  '/api/check': typeof ApiCheckRoute
  '/api/curiosidade': typeof ApiCuriosidadeRoute
  '/api/tts': typeof ApiTtsRoute
  '/api/vocab': typeof ApiVocabRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/conversa': typeof ConversaRoute
  '/curiosidades': typeof CuriosidadesRoute
  '/dashboard': typeof DashboardRoute
  '/flashcards': typeof FlashcardsRoute
  '/live': typeof LiveRoute
  '/quiz': typeof QuizRoute
  '/vocabulario': typeof VocabularioRoute
  '/api/chat': typeof ApiChatRoute
  '/api/check': typeof ApiCheckRoute
  '/api/curiosidade': typeof ApiCuriosidadeRoute
  '/api/tts': typeof ApiTtsRoute
  '/api/vocab': typeof ApiVocabRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/conversa'
    | '/curiosidades'
    | '/dashboard'
    | '/flashcards'
    | '/live'
    | '/quiz'
    | '/vocabulario'
    | '/api/chat'
    | '/api/check'
    | '/api/curiosidade'
    | '/api/tts'
    | '/api/vocab'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/conversa'
    | '/curiosidades'
    | '/dashboard'
    | '/flashcards'
    | '/live'
    | '/quiz'
    | '/vocabulario'
    | '/api/chat'
    | '/api/check'
    | '/api/curiosidade'
    | '/api/tts'
    | '/api/vocab'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/conversa'
    | '/curiosidades'
    | '/dashboard'
    | '/flashcards'
    | '/live'
    | '/quiz'
    | '/vocabulario'
    | '/api/chat'
    | '/api/check'
    | '/api/curiosidade'
    | '/api/tts'
    | '/api/vocab'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ConversaRoute: typeof ConversaRoute
  CuriosidadesRoute: typeof CuriosidadesRoute
  DashboardRoute: typeof DashboardRoute
  FlashcardsRoute: typeof FlashcardsRoute
  LiveRoute: typeof LiveRoute
  QuizRoute: typeof QuizRoute
  VocabularioRoute: typeof VocabularioRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiCheckRoute: typeof ApiCheckRoute
  ApiCuriosidadeRoute: typeof ApiCuriosidadeRoute
  ApiTtsRoute: typeof ApiTtsRoute
  ApiVocabRoute: typeof ApiVocabRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vocabulario': {
      id: '/vocabulario'
      path: '/vocabulario'
      fullPath: '/vocabulario'
      preLoaderRoute: typeof VocabularioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flashcards': {
      id: '/flashcards'
      path: '/flashcards'
      fullPath: '/flashcards'
      preLoaderRoute: typeof FlashcardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curiosidades': {
      id: '/curiosidades'
      path: '/curiosidades'
      fullPath: '/curiosidades'
      preLoaderRoute: typeof CuriosidadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversa': {
      id: '/conversa'
      path: '/conversa'
      fullPath: '/conversa'
      preLoaderRoute: typeof ConversaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vocab': {
      id: '/api/vocab'
      path: '/api/vocab'
      fullPath: '/api/vocab'
      preLoaderRoute: typeof ApiVocabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tts': {
      id: '/api/tts'
      path: '/api/tts'
      fullPath: '/api/tts'
      preLoaderRoute: typeof ApiTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/curiosidade': {
      id: '/api/curiosidade'
      path: '/api/curiosidade'
      fullPath: '/api/curiosidade'
      preLoaderRoute: typeof ApiCuriosidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/check': {
      id: '/api/check'
      path: '/api/check'
      fullPath: '/api/check'
      preLoaderRoute: typeof ApiCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ConversaRoute: ConversaRoute,
  CuriosidadesRoute: CuriosidadesRoute,
  DashboardRoute: DashboardRoute,
  FlashcardsRoute: FlashcardsRoute,
  LiveRoute: LiveRoute,
  QuizRoute: QuizRoute,
  VocabularioRoute: VocabularioRoute,
  ApiChatRoute: ApiChatRoute,
  ApiCheckRoute: ApiCheckRoute,
  ApiCuriosidadeRoute: ApiCuriosidadeRoute,
  ApiTtsRoute: ApiTtsRoute,
  ApiVocabRoute: ApiVocabRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
